name: CI-Deploy

on:
  push:
    branches:
      [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/github/resource-server/
            echo Recieved new update for resource-server
            (service resource-server status | grep "Active: active") && echo Stopping current process... && service resource-server stop
            (forever list | grep "resource-server") && forever stop resource-server
            echo Getting updates...
            git pull
            npm update
            echo Starting new process...
            sudo service resource-server start